=begin
#Live API Reference

#Reference for the Brightcove Live API, used to create and manage live streaming events.  For additional in-depth guides to features of the API, see the **[Support Site](https://support.brightcove.com/live-api)**.  **Base URL**: https://api.bcovlive.io/v1

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BrightcoveLive::ClipsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ClipsApi' do
  before do
    # run before each test
    @api_instance = BrightcoveLive::ClipsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClipsApi' do
    it 'should create an instance of ClipsApi' do
      expect(@api_instance).to be_instance_of(BrightcoveLive::ClipsApi)
    end
  end

  # unit tests for create_vod_clip
  # Create VOD Clip
  # Create VOD clips from a Live Stream. 
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param create_vod_clipbody Create VOD clips from a Live Stream.
  # @param [Hash] opts the optional parameters
  # @return [CreateVodJobResponse]
  describe 'create_vod_clip test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_vod_clip_alternate
  # Create VOD Clip (Alternate)
  # Create VOD clips from a Live Stream. This is operation is identical to the &#x60;POST&#x60; request to &#x60;/vods&#x60; - it is included for consistency, so that you can &#x60;GET&#x60; and &#x60;POST&#x60; requests to the same endpoint.
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param job_id Live job ID
  # @param create_vod_clipbody Create VOD clips from a Live Stream.
  # @param [Hash] opts the optional parameters
  # @return [VodJobs]
  describe 'create_vod_clip_alternate test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_vod_clip_job
  # Get VOD Clip Job
  # Get a VOD clip job by id. 
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param jvod_id VOD job ID
  # @param [Hash] opts the optional parameters
  # @return [VodJobs]
  describe 'get_vod_clip_job test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_vod_clips
  # List VOD Clip Jobs
  # List VOD clips for a Live Stream - for additional useful information on the search filters, see [Getting a List of Live or VOD Jobs](https://support.brightcove.com/getting-list-live-or-vod-jobs)
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param job_id Live job ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_token Next token from previous page; do not specify when fetching first page
  # @option opts [Integer] :page_size Max number of jobs to return in one request (1-1000, default is 10)
  # @option opts [String] :sort Attribute to sort jobs by (&#x60;created_at&#x60; | &#x60;modified_at&#x60;, default is &#x60;created_at&#x60;)
  # @option opts [String] :sort_dir Sort direction (default is asc):&#x60;asc&#x60; - ascending; &#x60;desc&#x60; - descending
  # @option opts [OneOfstringarray] :user_id Filter results by one or more user IDs
  # @option opts [String] :account_id Filter results by particular account, or specify ‘*’ to search all accounts.  Default value is account API key belongs to
  # @option opts [Integer] :created_at Filter results by Unix time of job creation (in milliseconds)
  # @option opts [Integer] :modified_at Filter results by Unix time of job last modified (in milliseconds)
  # @option opts [OneOfstringarray] :jvod_state Filter results by one or more VOD job states
  # @option opts [OneOfstringarray] :jvod_type Filter results by one or more VOD job types
  # @option opts [OneOfstringarray] :label Filter results by one or more VOD job labels
  # @return [ListVodJobs]
  describe 'list_vod_clips test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
