=begin
#Live API Reference

#Reference for the Brightcove Live API, used to create and manage live streaming events.

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for BrightcoveLive::CredentialsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CredentialsApi' do
  before do
    # run before each test
    @instance = BrightcoveLive::CredentialsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CredentialsApi' do
    it 'should create an instance of CredentialsApi' do
      expect(@instance).to be_instance_of(BrightcoveLive::CredentialsApi)
    end
  end

  # unit tests for create_credential
  # Create_Credential
  # Create a new credential. 
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {APIKey}
  # @param create_credentialbody Create a new credential.
  # @param [Hash] opts the optional parameters
  # @return [CreateCredential200]
  describe 'create_credential test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_credential
  # Delete_Credential
  # Delete a credential. 
  # @param credential_id A credential ID
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {APIKey}
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_credential test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_credentials
  # List_Credentials
  # This endpoint can be used to get user credentials for a given user provided one has an API key. 
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {APIKey}
  # @param [Hash] opts the optional parameters
  # @return [ListCredentials200]
  describe 'list_credentials test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_credential
  # Update_Credential
  # Update a credential. 
  # @param credential_id A credential ID
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {APIKey}
  # @param update_credentialbody Update a credential.
  # @param [Hash] opts the optional parameters
  # @return [UpdateCredential200]
  describe 'update_credential test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
