=begin
#Live API Reference

#Reference for the Brightcove Live API, used to create and manage live streaming events.

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::LiveJobsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LiveJobsApi' do
  before do
    # run before each test
    @instance = OpenapiClient::LiveJobsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LiveJobsApi' do
    it 'should create an instance of LiveJobsApi' do
      expect(@instance).to be_instance_of(OpenapiClient::LiveJobsApi)
    end
  end

  # unit tests for activate_sep_stream
  # Activate_SEP_Stream
  # Activate SEP (static entry point) Stream 
  # @param job_id Live job ID
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {APIKey}
  # @param [Hash] opts the optional parameters
  # @return [ActivateSepStream200]
  describe 'activate_sep_stream test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for cancel_live_job
  # Cancel_Live_Job
  # Cancel a live stream 
  # @param job_id Live job ID
  # @param x_api_key X-API-KEY: {APIKey}
  # @param [Hash] opts the optional parameters
  # @return [CancelLiveJob200]
  describe 'cancel_live_job test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_a_live_job
  # Create_a_Live_Job
  # Create a live stream 
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {APIKey}
  # @param create_a_live_jobbody Create a live stream
  # @param [Hash] opts the optional parameters
  # @return [CreateALiveJob200]
  describe 'create_a_live_job test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for deactivate_sep_stream
  # Deactivate_SEP_Stream
  # Deactivate SEP (static entry point) Stream 
  # @param job_id Live job ID
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {APIKey}
  # @param [Hash] opts the optional parameters
  # @return [DeactivateSepStream200]
  describe 'deactivate_sep_stream test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_live_job_details
  # Get_Live_Job_Details
  # Get Live Job Details 
  # @param job_id Live job ID
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {APIKey}
  # @param [Hash] opts the optional parameters
  # @return [Job]
  describe 'get_live_job_details test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for insert_id3_timed_metadata
  # Insert_ID3_timed_metadata
  # Inserts an ID3 timed metadata tag for an ongoing job. Note that: 1) If using timecode property, the job only stores the most recent request for insertion; 2) If using timecode property, the encoder must be sending SMPTE-formatted (HH:MM:SS:FF) timecode stored in the tc property via OnFI 
  # @param job_id Live job ID
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {APIKey}
  # @param insert_id3_timed_metadatabody Inserts an ID3 timed metadata tag for an ongoing job. Note that: 1) If using timecode property, the job only stores the most recent request for insertion; 2) If using timecode property, the encoder must be sending SMPTE-formatted (HH:MM:SS:FF) timecode stored in the tc property via OnFI
  # @param [Hash] opts the optional parameters
  # @return [InsertId3TimedMetadata200]
  describe 'insert_id3_timed_metadata test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_live_jobs
  # List_Live_Jobs
  # List live jobs - for additional useful information on the search filters, see [Getting a List of Live or VOD Jobs](https://support.brightcove.com/getting-list-live-or-vod-jobs)
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {APIKey}
  # @param [Hash] opts the optional parameters
  # @option opts [String] :start_token Next token from previous page; do not specify when fetching first page
  # @option opts [Integer] :page_size Max number of jobs to return in one request (1-1000, default is 10)
  # @option opts [String] :sort Attribute to sort jobs by (&#x60;created_at&#x60; | &#x60;modified_at&#x60;, default is &#x60;created_at&#x60;)
  # @option opts [String] :sort_dir Sort direction (default is asc):&#x60;asc&#x60; - ascending; &#x60;desc&#x60; - descending
  # @option opts [Object] :user_id Filter results by one or more user IDs
  # @option opts [String] :account_id Filter results by particular account, or specify ‘*’ to search all accounts.  Default value is account API key belongs to
  # @option opts [Integer] :created_at Filter results by Unix time of job creation (in milliseconds)
  # @option opts [Integer] :modified_at Filter results by Unix time of job last modified (in milliseconds)
  # @option opts [BOOLEAN] :ad_insertion Filter results by is SSAI enabled
  # @option opts [BOOLEAN] :static Filter results by has static endpoint
  # @option opts [Object] :state Filter results by one or more job states
  # @option opts [Object] :ssai_state Filter results by one or more SSAI states
  # @option opts [Object] :region Filter results by one or more regions
  # @return [ListLiveJobs200]
  describe 'list_live_jobs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for manual_ad_cue_point_insertion
  # Manual_Ad_Cue_Point_Insertion
  # Inserts a manual Cue-Out with a duration to the Live ingest point. 
  # @param job_id Live job ID
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {APIKey}
  # @param manual_ad_cue_point_insertionbody Inserts a manual Cue-Out with a duration to the Live ingest point.
  # @param [Hash] opts the optional parameters
  # @return [ManualAdCuePointInsertion200]
  describe 'manual_ad_cue_point_insertion test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
