=begin
#Live API Reference

#Reference for the Brightcove Live API, used to create and manage live streaming events.  For additional in-depth guides to features of the API, see the **[Support Site](https://support.brightcove.com/live-api)**.  **Base URL**: https://api.bcovlive.io/v1

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0

=end

require 'spec_helper'
require 'json'

# Unit tests for BrightcoveLive::SSAIApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SSAIApi' do
  before do
    # run before each test
    @api_instance = BrightcoveLive::SSAIApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SSAIApi' do
    it 'should create an instance of SSAIApi' do
      expect(@api_instance).to be_instance_of(BrightcoveLive::SSAIApi)
    end
  end

  # unit tests for create_ad_configuration
  # Create Ad Configuration
  # Create a configuration for server-side ad application. 
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param create_ad_configurationbody Create a configuration for server-side ad application.
  # @param [Hash] opts the optional parameters
  # @return [Application]
  describe 'create_ad_configuration test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_beacon_set
  # Create Beacon Set
  # Beacons are data points on playback sent to ad servers to track whether and how much of ads were played. Creates a beacon set.
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param create_beacon_setbody Beacons are data points on playback sent to ad servers to track whether and how much of ads were played. Creates a beacon set.
  # @param [Hash] opts the optional parameters
  # @return [CreateBeaconSetResponse]
  describe 'create_beacon_set test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_ad_configuration
  # Delete Ad Configuration
  # Delete an ad application. 
  # @param application_id The ad application id
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param [Hash] opts the optional parameters
  # @return [DeleteAdConfigurationResponse]
  describe 'delete_ad_configuration test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_beacon_set
  # Delete Beacon Set
  # Deletes a beacon set. 
  # @param beacon_set_id A slate media asset ID
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param [Hash] opts the optional parameters
  # @return [DeleteBeaconSetResponse]
  describe 'delete_beacon_set test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_slate_media_source_asset
  # Delete Slate Media Source Asset
  # Delete Slate Media Source Asset. 
  # @param slate_msa_id A slate media asset ID
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param [Hash] opts the optional parameters
  # @return [DeleteSlateMediaSourceAssetResponse]
  describe 'delete_slate_media_source_asset test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_account_ad_configurations
  # Get Account Ad Configurations
  # Get ad applications for an account. 
  # @param live_account_id Live account ID
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param [Hash] opts the optional parameters
  # @return [Application]
  describe 'get_account_ad_configurations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_ad_configuration
  # Get Ad Configuration
  # Get an ad application.
  # @param application_id The ad application id
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param [Hash] opts the optional parameters
  # @return [Application]
  describe 'get_ad_configuration test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_beacon_sets
  # Get Beacon Sets
  # Get all beacon sets for an account. 
  # @param live_account_id Live account ID
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param [Hash] opts the optional parameters
  # @return [BeaconSet]
  describe 'get_beacon_sets test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_beacon_sets_for_user
  # Get Beacon Sets for User
  # Get all beacon sets for the requesting user. 
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param [Hash] opts the optional parameters
  # @return [Array<BeaconSet>]
  describe 'get_beacon_sets_for_user test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_slates_for_account
  # Get Slates for Account
  # Get all beacon sets for an account. 
  # @param live_account_id Live account ID
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param [Hash] opts the optional parameters
  # @return [GetSlateMediaSourceAssetsResponse]
  describe 'get_slates_for_account test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_user_slate_media_source_assets
  # Get User Slate Media Source Assets
  # Get Slate Media Source Assets for the current user. 
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param [Hash] opts the optional parameters
  # @return [GetSlateMediaSourceAssetsResponse]
  describe 'get_user_slate_media_source_assets test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for getuser_ad_configurations
  # Get Ad Configurations
  # Get ad applications for the current user.
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param [Hash] opts the optional parameters
  # @return [Application]
  describe 'getuser_ad_configurations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for ingest_slate_media_source_asset
  # Ingest Slate Media Source Asset
  # Ingest Slate Media Source Asset. 
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param ingest_slate_media_source_assetbody Ingest Slate Media Source Asset.
  # @param [Hash] opts the optional parameters
  # @return [IngestSlateMediaSourceAssetResponse]
  describe 'ingest_slate_media_source_asset test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_ad_configuration
  # Update Ad Configuration
  # Update a configuration for server-side ad application. 
  # @param application_id The ad application id
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param update_ad_configurationbody Update a configuration for server-side ad application.
  # @param [Hash] opts the optional parameters
  # @return [Application]
  describe 'update_ad_configuration test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_beacon_set
  # Update Beacon Set
  # Updates a beacon set. 
  # @param beacon_set_id A slate media asset ID
  # @param content_type Content-Type: application/json
  # @param x_api_key X-API-KEY: {Your_Live_API_Key}
  # @param update_beacon_setbody Updates a beacon set.
  # @param [Hash] opts the optional parameters
  # @return [BeaconSet]
  describe 'update_beacon_set test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
