=begin
#Live API Reference

#Reference for the Brightcove Live API, used to create and manage live streaming events.

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BrightcoveLive::State
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'State' do
  before do
    # run before each test
    @instance = BrightcoveLive::State.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of State' do
    it 'should create an instance of State' do
      expect(@instance).to be_instance_of(BrightcoveLive::State)
    end
  end
end
