=begin
#Live API Reference

#Reference for the Brightcove Live API, used to create and manage live streaming events.

OpenAPI spec version: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.0.1

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/activate_sep_stream200'
require 'openapi_client/models/add_cdns'
require 'openapi_client/models/application'
require 'openapi_client/models/application_ad_configuration'
require 'openapi_client/models/application_application_ad_configuration'
require 'openapi_client/models/application_application_ad_configuration_ad_configuration_transforms'
require 'openapi_client/models/beacon_set'
require 'openapi_client/models/beacon_set_beacon_urls'
require 'openapi_client/models/beacon_sets'
require 'openapi_client/models/cancel_live_job200'
require 'openapi_client/models/create_a_live_job200'
require 'openapi_client/models/create_a_live_jobbody'
require 'openapi_client/models/create_a_live_jobbody_add_cdns'
require 'openapi_client/models/create_a_live_jobbody_add_cdns_token_auth'
require 'openapi_client/models/create_a_live_jobbody_add_cdns_token_auth_media'
require 'openapi_client/models/create_a_live_jobbody_encryption'
require 'openapi_client/models/create_a_live_jobbody_notifications'
require 'openapi_client/models/create_a_live_jobbody_outputs'
require 'openapi_client/models/create_a_live_jobbody_outputs_notifications'
require 'openapi_client/models/create_ad_configuration200'
require 'openapi_client/models/create_ad_configurationbody'
require 'openapi_client/models/create_ad_configurationbody_application_ad_configuration'
require 'openapi_client/models/create_ad_configurationbody_application_ad_configuration_ad_configuration_transforms'
require 'openapi_client/models/create_beacon_set200'
require 'openapi_client/models/create_beacon_setbody'
require 'openapi_client/models/create_beacon_setbody_beacon_urls'
require 'openapi_client/models/create_credential200'
require 'openapi_client/models/create_credentialbody'
require 'openapi_client/models/create_credentialbody_oauth_settings'
require 'openapi_client/models/create_vod_clip200'
require 'openapi_client/models/create_vod_clipbody'
require 'openapi_client/models/create_vod_clipbody2'
require 'openapi_client/models/create_vod_clipbody_outputs'
require 'openapi_client/models/create_vod_clipbody_outputs_videocloud'
require 'openapi_client/models/create_vod_clipbody_outputs_videocloud_ingest'
require 'openapi_client/models/create_vod_clipbody_outputs_videocloud_video'
require 'openapi_client/models/create_vod_clipbody_outputs_videocloud_video_cue_point'
require 'openapi_client/models/create_vod_clipbody_outputs_videocloud_video_geo'
require 'openapi_client/models/create_vod_clipbody_outputs_videocloud_video_schedule'
require 'openapi_client/models/credentials'
require 'openapi_client/models/cue_point'
require 'openapi_client/models/deactivate_sep_stream200'
require 'openapi_client/models/delete_ad_configuration200'
require 'openapi_client/models/delete_beacon_set200'
require 'openapi_client/models/delete_slate_media_source_asset200'
require 'openapi_client/models/economics'
require 'openapi_client/models/get_account_ad_configurations200'
require 'openapi_client/models/get_ad_configuration200'
require 'openapi_client/models/get_beacon_sets200'
require 'openapi_client/models/get_beacon_sets_for_user200'
require 'openapi_client/models/get_slate_media_source_assets200'
require 'openapi_client/models/id3_tag'
require 'openapi_client/models/ingest_slate_media_source_asset200'
require 'openapi_client/models/ingest_slate_media_source_assetbody'
require 'openapi_client/models/insert_id3_timed_metadata200'
require 'openapi_client/models/insert_id3_timed_metadatabody'
require 'openapi_client/models/insert_id3_timed_metadatabody_id3_tag'
require 'openapi_client/models/job'
require 'openapi_client/models/job_input_media_file'
require 'openapi_client/models/job_output_media_files'
require 'openapi_client/models/job_stream'
require 'openapi_client/models/job_stream_destination'
require 'openapi_client/models/job_stream_location'
require 'openapi_client/models/list_credentials200'
require 'openapi_client/models/list_live_jobs200'
require 'openapi_client/models/list_vod_jobs'
require 'openapi_client/models/manual_ad_cue_point_insertion200'
require 'openapi_client/models/manual_ad_cue_point_insertionbody'
require 'openapi_client/models/notifications'
require 'openapi_client/models/outputs'
require 'openapi_client/models/path'
require 'openapi_client/models/state'
require 'openapi_client/models/type'
require 'openapi_client/models/update_ad_configuration200'
require 'openapi_client/models/update_ad_configurationbody'
require 'openapi_client/models/update_ad_configurationbody_application_ad_configuration'
require 'openapi_client/models/update_ad_configurationbody_application_ad_configuration_ad_configuration_transforms'
require 'openapi_client/models/update_beacon_set200'
require 'openapi_client/models/update_beacon_setbody'
require 'openapi_client/models/update_beacon_setbody_beacon_urls'
require 'openapi_client/models/update_credential200'
require 'openapi_client/models/update_credentialbody'
require 'openapi_client/models/update_credentialbody_oauth_settings'
require 'openapi_client/models/vod_jobs'
require 'openapi_client/models/vod_jobs2'

# APIs
require 'openapi_client/api/clips_api'
require 'openapi_client/api/credentials_api'
require 'openapi_client/api/live_jobs_api'
require 'openapi_client/api/ssai_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
